name: publish
on: [push]
jobs:
publish-hello-docker-image:
runs-on: ubuntu-latest
steps:
  - uses: actions/checkout@v2
  - name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ De221 }}
password: ${{ secrets.WORKFLOW_SECRET }}
  - name: Build the hello-docker Docker image
run: |
  docker-compose up -d