name: publish
on:
  push:
    branches:
      - AddOns

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}

      - name: Build and publish the Docker image
        run: |
              cd Docker
              docker-compose up -d
              docker push ghcr.io/de221/findwork:latest